services:
  web:
    image: ironkey/web
    build:
      context: .
      dockerfile: apps/desktop/dockerfile.web
    restart: "no"
    ports:
      - "3000:80"

  backend:
    image: ironkey/backend
    build:
      context: .
      dockerfile: apps/backend/dockerfile
    restart: "no"
    ports:
      - "3333:3333"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:3333"]
      interval: 5s
      timeout: 10s
      retries: 5
    env_file:
      - apps/backend/.env.example
      - path: apps/backend/.env
        required: false
